Aarhus-Psychiatry-Research/psycop-feature-generation

pyproject.toml
src/psycop_feature_generation/timeseriesflattener/flattened_dataset.py

fix: pre code-split import statements need to be updated

---

example/loaders/load_coercion.py
pyproject.toml
src/psycop_feature_generation/data_checks/raw/check_raw_df.py
src/psycop_feature_generation/loaders/raw/load_coercion.py
src/psycop_feature_generation/loaders/raw/pre_load_dfs.py

Check raw dfs for duplicates across all or some columns

---

pyproject.toml
src/psycop_feature_generation/featurizers/tfidf.py
src/psycop_feature_generation/loaders/raw/load_text.py
tests/test_data/test_hf/test_hf_embeddings.py
tests/test_timeseriesflattener/test_add_values.py

Could not think of a better test for `test_add_hf_text_data()` for now since the output will depend on which model from HF one chooses to load. Might return and add more testing if I think of something great.

feat: add-huggingface-featurizer

---

src/psycop_feature_generation/timeseriesflattener/flattened_dataset.py

perf: use dask for concatenation

---

.github/workflows/main_test_and_release.yml
example/loaders/load_structured_sfi.py
src/psycop_feature_generation/loaders/raw/load_structured_sfi.py

@erikperfalk, vil du køre jeres test-script på Overtaci for at tjekke, at alting stadig fungerer? :-)

Refactor `load_structured_sfi`

---

src/psycop_feature_generation/loaders/raw/load_coercion.py

fix: deleted_irritating_blank_space

---

src/psycop_feature_generation/timeseriesflattener/flattened_dataset.py
src/psycop_feature_generation/timeseriesflattener/resolve_multiple_functions.py

fix: change_per_day function

---

example/loaders/load_admissions.py
src/psycop_feature_generation/loaders/raw/__init__.py
src/psycop_feature_generation/loaders/raw/load_admissions.py

Fixes #60
feat: new loader for admissions
Fixes #60 

Add loader for admissions

---

src/application/t2d/generate_features_and_write_to_disk.py
src/psycop_feature_generation/loaders/raw/pre_load_dfs.py

Fixes #64.
Two new features:
1. Start wandb run when starting script. Allows to use Wandb's Slack notifications to monitor whether script a run has errored
2. Only load unique dfs when pre-loading
And some misc. adjustments for my latest feature generation run.

fix: only load df once during preloading

---

CHANGELOG.md
pyproject.toml
src/application/t2d/generate_features_and_write_to_disk.py
src/psycop_feature_generation/data_checks/flattened/data_integrity.py
src/psycop_feature_generation/data_checks/raw/validate_raw_data.py
src/psycop_feature_generation/loaders/raw/pre_load_dfs.py
src/psycop_feature_generation/timeseriesflattener/flattened_dataset.py
tests/test_timeseriesflattener/test_resolve_multiple.py

fix: incorrect cache misses

---

.pre-commit-config.yaml
src/application/t2d/feature_spec_generator.py
src/application/t2d/generate_features_and_write_to_disk.py
src/psycop_feature_generation/timeseriesflattener/flattened_dataset.py

Add n HbA1c

---

src/psycop_feature_generation/timeseriesflattener/feature_spec_objects.py

Check specified loaders exist in registry

---

src/psycop_feature_generation/loaders/raw/load_admissions.py

changed timestamp to discharge day, rather than admission day.
Fixes #[129].

admission selected by discarge day

---

src/psycop_feature_generation/loaders/non_numerical_coercer.py

Removes a try/except error, which the debugger frequently got stuck on.

remove try/except to avoid debugger getting stuck on it

---

src/psycop_feature_generation/application_modules/filter_prediction_times.py
src/psycop_feature_generation/application_modules/flatten_dataset.py
src/psycop_feature_generation/application_modules/loggers.py
src/psycop_feature_generation/application_modules/project_setup.py
src/psycop_feature_generation/data_checks/flattened/feature_describer.py
src/psycop_feature_generation/loaders/example/load_diagnoses.py
src/psycop_feature_generation/loaders/raw/load_admissions.py
src/psycop_feature_generation/loaders/raw/load_coercion.py
src/psycop_feature_generation/loaders/raw/load_diagnoses.py
src/psycop_feature_generation/loaders/raw/load_moves.py
src/psycop_feature_generation/loaders/raw/utils.py
tests/test_feature_describer/test_feature_describer.py

Fixes #133.
Linting ended up changing a bunch of files, sorry about the messy diff. Main focus is:
1. Is this readable enough?
2. Does it solve the problem?

Keep only last visit in sequence for diagnoses to avoid data leakage from the future

---

src/psycop_feature_generation/loaders/raw/load_structured_sfi.py

Fixes #138 
Reversed 'elementledetdekst' and 'aktivitetstypenavn', added default val_col in loaders and added a loader with only physical threats from brøset.

reversed aktivitetstypenavn and elementledetekst fixed

---

src/psycop_feature_generation/loaders/raw/load_diagnoses.py

Fixes #140.
Check if the warning text covers what we want it to.

added warning message about granularity issue when loading diagnoses

---

src/psycop_feature_generation/loaders/raw/load_diagnoses.py
src/psycop_feature_generation/loaders/raw/utils.py

Added arguments in load_from_codes in utils and in diagnosis loaders in load_diagnoses so we can filter on shak codes.

added arguments so we can filter diagnoses on shak codes

---

src/psycop_feature_generation/loaders/raw/load_visits.py

Merging of load_admissions and load_visits. Load_visits is subsettable by visit type and can return visit time in days if specified, instead of 1.

merge load_visits and load_admissions

---

src/psycop_feature_generation/loaders/raw/load_diagnoses.py

Warning is quite wordy, let me know if you have suggestions.

Add arg for timestamp selection

---

src/psycop_feature_generation/loaders/raw/load_visits.py

fix: loader names too long for wandb

---

src/psycop_feature_generation/loaders/raw/load_visits.py

fix: loader names still too long

---

src/psycop_feature_generation/loaders/raw/load_visits.py

change timestamps_only arg to default false

---

src/psycop_feature_generation/data_checks/flattened/feature_describer.py

- [ YES] I have battle-tested on Overtaci (RMAPPS1279)
- [ NO] I have assigned ranges (e.g. `>=0.1, <0.2`) to all new dependencies (allows dependabot to keep dependency ranges wide for better compatability)

corrected exists_ok to exist_ok

---

src/psycop_feature_generation/application_modules/flatten_dataset.py

See reasoning in #general on Slack.

fix: disable cache

---

src/psycop_feature_generation/loaders/raw/load_coercion.py

Add skema_2_without_nutrition loader again.

fix: add skema_2_without_nutrition again

---

src/psycop_feature_generation/loaders/raw/load_coercion.py

Remove unintended space before "Af helbredsmæssige grunde".

Remove space

---

src/psycop_feature_generation/data_checks/flattened/feature_describer.py

refactor: rename variable

---

src/psycop_feature_generation/loaders/raw/load_structured_sfi.py

As with weight, it seems there are some data entry errors in the BMI data. I'm not sure about the cut-offs of > 10 and < 70. What do you think? 😊

fix: remove unreasonably high or low bmi values

---

.cruft.json
.github/recommended_repo_setup.md
.github/workflows/cruft.yml
.github/workflows/pre-commit.yml
.github/workflows/stalebot.yml
.pre-commit-config.yaml
README.md.rej
pyproject.toml.rej
src/psycop_feature_generation/__init__.py.rej
tasks.py
tasks.py.rej

ci - update cruft

---

src/psycop_feature_generation/application_modules/filter_prediction_times.py
src/psycop_feature_generation/application_modules/flatten_dataset.py

refactor: minor
